//keys : 0: name, 1: type, 2: price, 3: description, 4: url, 5: img location

var relatedProducts = [
  ["iPhone 6s (128 GB)","cellphone","949","The moment you use iPhone 6s, you know you’ve never felt anything like it. With a single press, 3D Touch lets you do more than ever before. Live Photos bring your memories to life in a powerfully vivid way. And that’s just the beginning. Take a deeper look at iPhone 6s, and you’ll find innovation on every level.","http://www.apple.com/shop/buy-iphone/iphone6s/5.5-inch-display-128gb-silver-att","iphone.jpg"  ],
  ["Alma by Louis Vuitton","purse","1810","The most structured of the iconic Louis Vuitton handbags, the Alma was originally designed in the 1930s by Gaston-Louis Vuitton. Named after the Alma bridge over the river Seine, it captures the essence of Parisian chic in Monogram canvas. Ideal for contemporary women, the medium-sized Alma bag will hold all everyday essentials.","http://us.louisvuitton.com/eng-us/products/alma-mm-monogram-007737","alma.jpg"  ],
  ["Richard Hennessy","cognac","4800","A tribute to the Founder of Hennessy, Richard Hennessy is a unique assemblage of more than 100 of the most exceptional eaux-de-vie, matured to the fullest. The oldest of these are extremely rare, and some date from the early 19th century. Balanced and complex, the rich bouquet slowly releases a succession of aromas that have built up over the years: vanilla, spices, pepper and delicately fragrant flowers.","http://www.reservebar.com/<products/hennessy-richard-hennessy","hennessy.jpg"  ],
  ["Cle de Cartier","watch","9650","Cartier continues to reign as the master of watches with its latest collection, Clé de Cartier. With soft curves, clean lines, and a rounded profile, the Clé exudes a minimalist elegance. The design is a testament to precision, balance, and proportion. Great mastery went into creating fluid lines and a harmonious design. The Clé de Cartier owes its name to its distinct crown and houses the caliber 1847 MC, the new Cartier Manufacture Movement.","http://www.cartier.us/en-us/collections/gifts/for-him/holiday-gifts-him/w2cl0002-cle-de-cartier-watch.html","cartier.png"  ],
  ["The Tiffany Setting with Diamond Band","jewelry","15000","A band of channel-set round brilliant diamonds enhances the classic Tiffany six-prong setting for a spectacular display of white light.","http://www.tiffany.com/engagement/rings/the-tiffany-setting-with-diamond-band?origin=engagement&search_params=param+0/0/0/0/0/0","tiffany.jpg"  ],
  ["Toyota Prius Five","car","30000","Prius changed the world 15 years ago by bringing hybrid cars to the mainstream. It’s a modern-day icon, and its Hybrid Synergy Drive® remains innovative, dependable and loved by owners around the world. That’s why 95% of all Toyota Prius models sold in the last 10 years are still on the road.","http://www.toyota.com/prius/","prius.jpg"  ]
]